import type {
  Holding,
  HoldingExposureInput,
  TargetAllocation,
} from "@/lib/domain";

export const sampleHoldings: Holding[] = [
  {
    id: "h-xeqt-tfsa",
    ticker: "XEQT",
    name: "iShares Core Equity ETF Portfolio",
    accountId: "tfsa",
    accountName: "TFSA",
    accountType: "TFSA",
    currency: "CAD",
    units: 120,
    price: 33.81,
    marketValue: 4057.2,
    averageCost: 32.15,
    costBasis: 3858,
    unrealizedGainLoss: 199.2,
    latestPriceDate: "2026-04-15T00:00:00.000Z",
  },
  {
    id: "h-xbb-tfsa",
    ticker: "XBB",
    name: "iShares Core Canadian Universe Bond Index ETF",
    accountId: "tfsa",
    accountName: "TFSA",
    accountType: "TFSA",
    currency: "CAD",
    units: 40,
    price: 29.17,
    marketValue: 1166.8,
    averageCost: 28.94,
    costBasis: 1157.6,
    unrealizedGainLoss: 9.2,
    latestPriceDate: "2026-04-15T00:00:00.000Z",
  },
  {
    id: "h-xeqt-rrsp",
    ticker: "XEQT",
    name: "iShares Core Equity ETF Portfolio",
    accountId: "rrsp",
    accountName: "RRSP",
    accountType: "RRSP",
    currency: "CAD",
    units: 35,
    price: 33.81,
    marketValue: 1183.35,
    averageCost: 33.05,
    costBasis: 1156.75,
    unrealizedGainLoss: 26.6,
    latestPriceDate: "2026-04-15T00:00:00.000Z",
  },
  {
    id: "h-xaw-rrsp",
    ticker: "XAW",
    name: "iShares Core MSCI All Country World ex Canada Index ETF",
    accountId: "rrsp",
    accountName: "RRSP",
    accountType: "RRSP",
    currency: "CAD",
    units: 28,
    price: 42.44,
    marketValue: 1188.32,
    averageCost: 41.88,
    costBasis: 1172.64,
    unrealizedGainLoss: 15.68,
    latestPriceDate: "2026-04-15T00:00:00.000Z",
  },
  {
    id: "h-vcn-taxable",
    ticker: "VCN",
    name: "Vanguard FTSE Canada All Cap Index ETF",
    accountId: "taxable",
    accountName: "Taxable",
    accountType: "TAXABLE",
    currency: "CAD",
    units: 22,
    price: 48.09,
    marketValue: 1057.98,
    averageCost: 47.25,
    costBasis: 1039.5,
    unrealizedGainLoss: 18.48,
    latestPriceDate: "2026-04-15T00:00:00.000Z",
  },
];

export const sampleTargetAllocations: TargetAllocation[] = [
  { ticker: "XEQT", targetWeight: 0.55 },
  { ticker: "XBB", targetWeight: 0.25 },
  { ticker: "VCN", targetWeight: 0.1 },
  { ticker: "XAW", targetWeight: 0.1 },
];

export const sampleHoldingExposures: HoldingExposureInput[] = [
  { ticker: "XEQT", exposureType: "ASSET_CLASS", exposureName: "Equity", weight: 1 },
  { ticker: "XEQT", exposureType: "REGION", exposureName: "Canada", weight: 0.24 },
  { ticker: "XEQT", exposureType: "REGION", exposureName: "United States", weight: 0.46 },
  {
    ticker: "XEQT",
    exposureType: "REGION",
    exposureName: "International Developed",
    weight: 0.21,
  },
  { ticker: "XEQT", exposureType: "REGION", exposureName: "Emerging Markets", weight: 0.09 },
  {
    ticker: "XBB",
    exposureType: "ASSET_CLASS",
    exposureName: "Fixed Income",
    weight: 1,
  },
  { ticker: "XBB", exposureType: "REGION", exposureName: "Canada", weight: 1 },
  {
    ticker: "VCN",
    exposureType: "ASSET_CLASS",
    exposureName: "Equity",
    weight: 1,
  },
  { ticker: "VCN", exposureType: "REGION", exposureName: "Canada", weight: 1 },
  {
    ticker: "XAW",
    exposureType: "ASSET_CLASS",
    exposureName: "Equity",
    weight: 1,
  },
  { ticker: "XAW", exposureType: "REGION", exposureName: "United States", weight: 0.63 },
  {
    ticker: "XAW",
    exposureType: "REGION",
    exposureName: "International Developed",
    weight: 0.26,
  },
  { ticker: "XAW", exposureType: "REGION", exposureName: "Emerging Markets", weight: 0.11 },
];
